apiVersion: networking.k8s.io/v1beta1
kind: Ingress
metadata:
  name: podinfo
spec:
  rules:
    - host: podinfo.apps.openshift.bvb.local
      http:
        paths:
          - path: /
            backend:
              serviceName: podinfo
              servicePort: http